name: publish

on:
  # For the timebeing only trigger on repo dispatch,
  # introduce versioning if you want to automate
  repository_dispatch:
    types:
      - trigger:publish

env:
  CI: true

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@parsleyhealth'

      - name: Publish to GitHub Package Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn publish
